version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_api_rest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_api_rest:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

volumes:
  mongodb_api_rest:
